server:
  port: 8080

security:
  secret: 01234567890123456789012345678901234567890123456789012345678901234567890123456789
  expiration-ms: 3600000

metrics-aspects:
  kafka-topic: t1_demo_metrics
  time-limit-ms: 5
  enable-data-source-error-logging: true
  enable-time-limit-exceed-error-logging: true
  initialize-db-schema: true

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 123
    username: postgres
    url: jdbc:postgresql://localhost:5432/t1_homeworks_service_1_db

  devtools:
    livereload:
      port: 35729

  application:
    name: t1-homeworks-service-1
    cache:
      timeout-sec: 10
    kafka:
      transaction-accept-topic: t1_demo_transaction_accept
    transactions:
      max-rejected: 4
    external-services:
      service-2:
        base-url: http://localhost:8081/api/

  flyway:
    baseline-on-migrate: true
    baseline-version: 0

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      retries: 3
      properties:
        retry.backoff.ms: 1000
        enable.idempotence: false
    consumer:
      group-id: t1_demo
      properties:
        session.timeout.ms: 10000
        max.partition.fetch.bytes: 300000
        max.poll.records: 10
        max.poll.interval.ms: 300000
        heartbeat.interval.ms: 3000

logging:
  level:
    ROOT: info
