spring:
  application:
    name: t1-homeworks
    metrics:
      time-limit-ms: 5
    cache:
      timeout-sec: 10
    kafka:
      metrics-topic: t1_demo_metrics

  flyway:
    baseline-on-migrate: true
    baseline-version: 0

  jpa:
    hibernate:
      ddl-auto: validate

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      retries: 3
      properties:
        retry.backoff.ms: 1000
        enable.idempotence: false
