spring:
  application:
    name: t1-homeworks
    metrics:
      time-limit-ms: 5
    cache:
      timeout-sec: 10
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
  jpa:
    hibernate:
      ddl-auto: validate