scrape_configs:
  - job_name: 't1-homeworks-service-1'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s # This can be adjusted based on our needs
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]
        labels:
          alias: "t1_homeworks_service_1"