CREATE TABLE transaction
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    transaction_id UUID                                    NOT NULL,
    timestamp      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    status         VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_transaction PRIMARY KEY (id)
);

ALTER TABLE transaction
    ADD CONSTRAINT uc_transaction_transaction UNIQUE (transaction_id);