server:
  port: 8082

spring:
  devtools:
    livereload:
      port: 35731

  application:
    name: t1-homeworks-service-3
    unblock:
      client-unblock-probability: 0.7
      account-unblock-probability: 0.3
