CREATE TABLE time_limit_exceed_log
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    method_signature TEXT                                    NOT NULL,
    measured_time_ms DOUBLE PRECISION                        NOT NULL,
    logged_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_time_limit_exceed_log PRIMARY KEY (id)
);